// This file is generated by scripts/set-env.js from the repo-root .env file.
// Do not edit by hand, changes are overwritten on the next `npm start`/`npm run build`.

export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:3000',
};
