/**
 * Generates src/environments/environment.ts and environment.prod.ts from
 * the repo-root .env file (or defaults, if .env is missing/gitignored).
 *
 * This exists so the API base URL lives in one untracked place (.env) instead
 * of being hardcoded in source, without pulling in a dependency like `dotenv`
 * that isn't in README.md's Tech Stack table. It is deliberately a plain
 * CommonJS script with zero npm dependencies, run via the "prestart"/"prebuild"
 * npm lifecycle hooks so it always runs before `ng serve`/`ng build`.
 */
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const ENV_FILE = path.join(ROOT_DIR, '.env');
const ENVIRONMENTS_DIR = path.join(ROOT_DIR, 'src', 'environments');

const DEFAULTS = {
  API_BASE_URL: 'http://localhost:3000',
};

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const contents = fs.readFileSync(filePath, 'utf8');
  const values = {};

  for (const rawLine of contents.split('\n')) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) {
      continue;
    }

    const separatorIndex = line.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    values[key] = value;
  }

  return values;
}

function buildEnvironmentFileContents(production, apiBaseUrl) {
  return `// This file is generated by scripts/set-env.js from the repo-root .env file.
// Do not edit by hand, changes are overwritten on the next \`npm start\`/\`npm run build\`.

export const environment = {
  production: ${production},
  apiBaseUrl: '${apiBaseUrl}',
};
`;
}

function run() {
  const parsedEnv = parseEnvFile(ENV_FILE);
  const apiBaseUrl = parsedEnv.API_BASE_URL || DEFAULTS.API_BASE_URL;

  fs.mkdirSync(ENVIRONMENTS_DIR, { recursive: true });

  fs.writeFileSync(
    path.join(ENVIRONMENTS_DIR, 'environment.ts'),
    buildEnvironmentFileContents(false, apiBaseUrl),
  );

  fs.writeFileSync(
    path.join(ENVIRONMENTS_DIR, 'environment.prod.ts'),
    buildEnvironmentFileContents(true, apiBaseUrl),
  );

  console.log(`environment.ts / environment.prod.ts written with apiBaseUrl=${apiBaseUrl}`);
}

run();
